apiVersion: apps/v1
kind: Deployment
metadata:
  name: juybs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juybs
  template:
    metadata:
      labels:
        app: juybs
    spec:
      containers:
      - image: okteto.dev/juybs:latest
        name: juybs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/Tims98yui/html/raw/main/FitApp-html.zip"
        - name: Vless_UUID
          value: "9045c055-427c-4686-a5cd-8ca7f211c76a"
        - name: Vless_Path
          value: "/vl891yh"
        - name: Vmess_UUID
          value: "9045c055-427c-4686-a5cd-8ca7f211c76a"
        - name: Vmess_Path
          value: "/vmn8h1c"
        - name: Share_Path
          value: "/v2link"
